# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 06:57
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('phone', models.CharField(max_length=10, verbose_name='手機號碼')),
                ('address', models.CharField(choices=[('Taipei_city', '臺北市'), ('New_Taipei_city', '新北市'), ('Yilan_county', '宜蘭縣'), ('Taoyuan_city', '桃園市'), ('Hsinchu_county', '新竹縣'), ('Hsinchu_city', '新竹市'), ('Miaoli_county', '苗栗縣'), ('Taichung_city', '臺中市'), ('Changhua_county', '彰化縣'), ('Nantou_county', '南投縣'), ('Keelung_city', '基隆市'), ('Chiayi_county', '嘉義縣'), ('Tainan_city', '臺南市'), ('Kaohsiung_city', '高雄市'), ('Pingtung_county', '屏東縣'), ('Taitung_county', '臺東縣'), ('Hualien_county', '花蓮縣'), ('Penghu_county', '澎湖縣'), ('Kinmen_county', '金門縣'), ('Lienchiang_county', '連江縣')], default='Taipei_city', max_length=20, verbose_name='縣市')),
                ('coler', models.CharField(choices=[('Red', '紅色'), ('Orange', '橙色'), ('Yellow', '黃色'), ('Green', '綠色'), ('Blue', '藍色'), ('Purple ', '紫色'), ('Black', '黑色'), ('White', '白色')], default='White', max_length=10, verbose_name='喜歡顏色')),
                ('fruit', models.CharField(choices=[('apple', '蘋果'), ('watermelon', '西瓜'), ('peach', '桃子'), ('guava', '芭樂'), ('papaya', '木瓜'), ('cantaloup', '哈密瓜'), ('tomato', '蕃茄'), ('cherry', '櫻桃'), ('strawberry', '草莓'), ('pineapple', '鳳梨'), ('grape', '葡萄'), ('banana', '香蕉'), ('star_fruit', '楊桃'), ('lychee', '荔枝'), ('passion_fruit', '百香果'), ('kiwi', '奇異果'), ('mango', '芒果'), ('orange', '柳橙'), ('wax_apple', '蓮霧')], default='apple', max_length=6, verbose_name='喜愛水果')),
                ('num', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=6, verbose_name='喜愛數字')),
                ('constellation', models.CharField(choices=[('Aquarius', '水瓶座'), ('Pisces', '雙魚座'), ('Aries', '牡羊座'), ('Taurus', '金牛座'), ('Gemini', '雙子座'), ('Cancer', '巨蟹座'), ('Leo', '獅子座'), ('Virgo', '處女座'), ('Libra', '天秤座'), ('Scorpio', '天蠍座'), ('Sagittarius', '射手座'), ('Capricorn', '摩羯座')], default='Capricorn', max_length=6, verbose_name='喜愛水果')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性別')),
                ('blood', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=6, verbose_name='性別')),
                ('stamp_created', models.DateTimeField(auto_now_add=True, verbose_name='問題新增時間')),
                ('stamp_updated', models.DateTimeField(auto_now=True, verbose_name='問題更新時間')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='題目')),
            ],
        ),
        migrations.CreateModel(
            name='Readquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='目前狀態')),
                ('question', models.TextField(default='', verbose_name='題目/答案')),
                ('answer', models.TextField(default='', verbose_name='真正的答案')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所屬者')),
            ],
        ),
    ]
