# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20180331_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readquestion',
            name='answer',
            field=models.TextField(blank=True, default='', null=True, verbose_name='真正的答案'),
        ),
        migrations.AlterField(
            model_name='readquestion',
            name='question',
            field=models.TextField(blank=True, default='', null=True, verbose_name='題目/答案'),
        ),
    ]
