# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20180331_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.CharField(choices=[('Elementary', '國小'), ('secondary', '國中'), ('High_school', '高中'), ('Vocational', '高職'), ('University', '大學'), ('HKUST', '科大'), ('master', '碩士生'), ('PhD_student', '博士生')], default='University', max_length=20, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='num',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=6, verbose_name='喜愛數字'),
        ),
    ]
