# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20180331_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blood',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=6, verbose_name='血型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(choices=[('Elementary', '國小'), ('secondary', '國中'), ('High_school', '高中'), ('Vocational', '高職'), ('University', '大學'), ('HKUST', '科大'), ('master', '碩士生'), ('PhD_student', '博士生')], default='University', max_length=20, verbose_name='學歷'),
        ),
    ]
