# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_userprofile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(choices=[('臺北市', '臺北市'), ('新北市', '新北市'), ('宜蘭縣', '宜蘭縣'), ('桃園市', '桃園市'), ('新竹縣', '新竹縣'), ('新竹市', '新竹市'), ('苗栗縣', '苗栗縣'), ('臺中市', '臺中市'), ('彰化縣', '彰化縣'), ('南投縣', '南投縣'), ('基隆市', '基隆市'), ('嘉義縣', '嘉義縣'), ('臺南市', '臺南市'), ('高雄市', '高雄市'), ('屏東縣', '屏東縣'), ('臺東縣', '臺東縣'), ('花蓮縣', '花蓮縣'), ('澎湖縣', '澎湖縣'), ('金門縣', '金門縣'), ('連江縣', '連江縣')], default='臺北市', max_length=20, verbose_name='縣市'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='coler',
            field=models.CharField(choices=[('紅色', '紅色'), ('橙色', '橙色'), ('黃色', '黃色'), ('綠色', '綠色'), ('藍色', '藍色'), ('紫色 ', '紫色'), ('黑色', '黑色'), ('白色', '白色')], default='紅色', max_length=10, verbose_name='喜歡顏色'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='constellation',
            field=models.CharField(choices=[('水瓶座', '水瓶座'), ('雙魚座', '雙魚座'), ('牡羊座', '牡羊座'), ('金牛座', '金牛座'), ('雙子座', '雙子座'), ('巨蟹座', '巨蟹座'), ('獅子座', '獅子座'), ('處女座', '處女座'), ('天秤座', '天秤座'), ('天蠍座', '天蠍座'), ('射手座', '射手座'), ('摩羯座', '摩羯座')], default='水瓶座', max_length=20, verbose_name='喜愛水果'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(choices=[('國小', '國小'), ('國中', '國中'), ('高中', '高中'), ('高職', '高職'), ('大學', '大學'), ('科大', '科大'), ('碩士生', '碩士生'), ('博士生', '博士生')], default='大學', max_length=20, verbose_name='學歷'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fruit',
            field=models.CharField(choices=[('蘋果', '蘋果'), ('西瓜', '西瓜'), ('桃子', '桃子'), ('芭樂', '芭樂'), ('木瓜', '木瓜'), ('哈密瓜', '哈密瓜'), ('蕃茄', '蕃茄'), ('櫻桃', '櫻桃'), ('草莓', '草莓'), ('鳳梨', '鳳梨'), ('葡萄', '葡萄'), ('香蕉', '香蕉'), ('楊桃', '楊桃'), ('荔枝', '荔枝'), ('百香果', '百香果'), ('奇異果', '奇異果'), ('芒果', '芒果'), ('柳橙', '柳橙'), ('蓮霧', '蓮霧')], default='草莓', max_length=20, verbose_name='喜愛水果'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=6, verbose_name='性別'),
        ),
    ]
