# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20180331_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='token',
        ),
        migrations.AddField(
            model_name='readquestion',
            name='teamate',
            field=models.CharField(default='', max_length=10, verbose_name='對應對手'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=0, verbose_name='分數'),
        ),
    ]
